metadataPackage_1593448409706/objects/Object_Tag__c.object
<CustomObject>
    <description>Captures notation/application of a Tag to a particular Object record. Junction object b/w Tag and other objects.</description>
    <label>Object Tag</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Object Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Tag</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Tag__c</fullName>
        <label>Tag</label>
        <referenceTo>Tag__c</referenceTo>
        <relationshipLabel>Object Tag</relationshipLabel>
        <relationshipName>Object_Tag</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

metadataPackage_1593448409706/objects/Tag__c.object
<CustomObject>
    <description>predefined tag that are designed to be applied on certain objects for variety of business notations</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Displayed to the user while applying Tag to a given Object, or when viewing tags that are applied already.</description>
        <inlineHelpText>Displayed to the user while applying Tag to a given Object, or when viewing tags that are applied already.</inlineHelpText>
        <label>Help Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tag_Color__c</fullName>
        <label>Tag Color</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>White</fullName>
                    <default>true</default>
                    <label>White</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Pink</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/TagItTest.cls
@isTest
public class TagItTest {

    @testSetup 
    static void setup() {
        // Create common test accounts
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
       
        User u = new User(Alias = 'standt', Email='kamipatel@gmail.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='tagtest@salesforce.com');
        insert u;
       
        // Query your permission set name from Organization that your want to test.
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'TagitPerms'];
       
        // Assign the above inserted user for the above Permission Set.
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;

    }

    @isTest 
    static void testTagFunctions() {

        User u = [select Id, Email from User where Email='kamipatel@gmail.com' limit 1];

        System.runAs(u)
        {
            Test.startTest();

            Account a = new Account(Name = 'TestAcct');        
            insert a;
    
            Tag__c t = new Tag__c();        
            t.Name = 'High Profile';
            t.Active__c = true;
            t.Tag_Color__c= 'Green';         
            t.Help_Text__c = 'high profile help';
            insert t;

            TagHelper th = new TagHelper();
            
            
            List<Tag__c> tags = TagHelper.getTags();
            System.assertEquals(1, tags.size());

            String oId = TagHelper.CreateTagLink(a.Id, t.id);

            List<Object_Tag__c> accountTags = TagHelper.getAccountTags(a.Id);
            System.assertEquals(1, accountTags.size());


            TagHelper.SoftDeleteLink(oId);            

            TagHelper.getSomething('DummySuccess');

            Test.stopTest();
        }
    }

    
}